apiVersion: apiextensions.k8s.io/v1    
kind: CustomResourceDefinition
metadata:
  name: backuppolicies.ops.abchatterjee7
spec:
  group: ops.abchatterjee7
  names:
    plural: backuppolicies
    singular: backuppolicy
    kind: BackupPolicy
    shortNames:
      - bp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schedule:
                  type: string
                  description: Cron format (e.g., "0 1 * * *")
                retentionDays:
                  type: integer
                  description: Number of days to retain backups
                targetPVC:
                  type: string
                  description: Name of the PVC to back up